-- Create territories table
CREATE TABLE IF NOT EXISTS territories (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id INT UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  color VARCHAR(7),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_territories_tenant ON territories (tenant_id);

-- Add territory_id to shops
ALTER TABLE shops ADD COLUMN territory_id INT UNSIGNED NULL AFTER agent_id;
ALTER TABLE shops ADD FOREIGN KEY (territory_id) REFERENCES territories(id) ON DELETE SET NULL;
