# -*- coding: utf-8 -*-
"""Содержание руководства по ролям: одна структура — два языка (ru, uz), один набор снимков."""

# img: (web|mobile, role, screen) — путь снимка подставляется по языку.
GUIDE = [
  {
    "key": "start", "ru": "Как начать", "uz": "Qanday boshlash",
    "intro": ("Вход один для всех ролей: адрес компании, e-mail и пароль. После входа каждый видит только свои экраны. Язык переключается внизу меню (веб) или в профиле (телефон).",
              "Kirish barcha rollar uchun bir xil: kompaniya manzili, e-mail va parol. Kirgandan so'ng har kim faqat o'z ekranlarini ko'radi. Til menyuning pastida (veb) yoki profilda (telefon) almashtiriladi."),
    "steps": [
      {"ru": "Веб: откройте адрес компании, введите e-mail и пароль. Если включена двухфакторная защита — код из приложения.",
       "uz": "Veb: kompaniya manzilini oching, e-mail va parolni kiriting. Ikki bosqichli himoya yoqilgan bo'lsa — ilovadagi kod.",
       "img": ("web", "login", "login")},
      {"ru": "Телефон: тот же e-mail и пароль. Приложение запоминает вход; повторный вход — по отпечатку или Face ID.",
       "uz": "Telefon: o'sha e-mail va parol. Ilova kirishni eslab qoladi; qayta kirish — barmoq izi yoki Face ID orqali.",
       "img": ("mobile", "agent", "login")},
      {"ru": "Язык: в вебе — кнопки РУС / UZB внизу меню; на телефоне — Профиль → Язык.",
       "uz": "Til: vebda — menyu pastidagi РУС / UZB tugmalari; telefonda — Profil → Til.",
       "img": ("mobile", "agent", "profile")},
    ],
  },
  {
    "key": "operator", "ru": "Оператор офиса и склад", "uz": "Ofis operatori va ombor",
    "intro": ("Оператор живёт в «Заказах»: принимает и проверяет заказы агентов, собирает погрузочные листы, отдаёт рейсы курьерам, проводит приходы и возвраты.",
              "Operator «Buyurtmalar»da ishlaydi: agentlarning buyurtmalarini qabul qilib tekshiradi, yuklash varaqalarini yig'adi, reyslarni kuryerlarga beradi, kirim va qaytarishlarni o'tkazadi."),
    "steps": [
      {"ru": "Заказы. Сводка одной строкой — каждое число фильтр: «Ожидает» — заказы, которые ждут решения офиса (например, скидка выше порога). Клик по строке открывает панель заказа; в панели у ожидающего — причина и кнопки «Подтвердить / Отклонить».",
       "uz": "Buyurtmalar. Bir qatorli xulosa — har bir raqam filtr: «Kutmoqda» — ofis qarorini kutayotgan buyurtmalar (masalan, chegirma chegaradan yuqori). Qatorga bosilsa buyurtma paneli ochiladi; kutayotgan buyurtmada — sabab va «Tasdiqlash / Rad etish» tugmalari.",
       "img": ("web", "operator", "orders")},
      {"ru": "Новый заказ по звонку: магазин (поиск по названию, владельцу, телефону; рядом долг), товары (видно «свободно N»), способ оплаты — готово.",
       "uz": "Qo'ng'iroq bo'yicha yangi buyurtma: do'kon (nomi, egasi, telefoni bo'yicha qidiruv; yonida qarz), tovarlar («bo'sh N» ko'rinadi), to'lov usuli — tayyor.",
       "img": ("web", "operator", "order-new")},
      {"ru": "Погрузочный лист: отметьте заказы галочками → «Погрузочные листы» → «Сформировать лист» → печать. Лист держит свои заказы, пока не закрыт; собрать их второй раз нельзя.",
       "uz": "Yuklash varaqasi: buyurtmalarni belgilang → «Yuklash varaqalari» → «Varaqa tuzish» → chop etish. Varaqa yopilguncha o'z buyurtmalarini ushlab turadi; ularni ikkinchi marta yig'ib bo'lmaydi.",
       "img": None},
      {"ru": "Сборка по строкам: в списке листов у листа «готовится» — кнопка «Собрать». Строки: нужно / партии (по FEFO — те же, что спишет отгрузка) / собрано. Меньше нужного — недостача: она видна в списке и уходит офису уведомлением. Затем — курьер на весь лист одним выбором.",
       "uz": "Qatorlar bo'yicha yig'ish: varaqalar ro'yxatida «tayyorlanmoqda» varaqada — «Yig'ish» tugmasi. Qatorlar: kerak / partiyalar (FEFO bo'yicha — jo'natishda hisobdan chiqariladigan o'shalar) / yig'ildi. Kerakdan kam — kamomad: u ro'yxatda ko'rinadi va ofisga bildirishnoma bo'lib boradi. So'ng — butun varaqaga bitta tanlov bilan kuryer.",
       "img": None},
      {"ru": "Приход товара: «Приходы» → новая накладная, товар по коду или сканером, партия и срок годности → «Сохранить и завершить». Остаток меняется только после завершения.",
       "uz": "Tovar kirimi: «Kirim» → yangi nakladnoy, tovar kodi yoki skaner bilan, partiya va yaroqlilik muddati → «Saqlash va yakunlash». Qoldiq faqat yakunlangandan keyin o'zgaradi.",
       "img": ("web", "operator", "arrivals")},
      {"ru": "Склад: остатки, партии и сроки; «Отчёты по складу» — что сгорает. Возвраты от магазинов проводит офис; возврат поставщику — из карточки поставщика в «Приходах».",
       "uz": "Ombor: qoldiqlar, partiyalar va muddatlar; «Ombor hisobotlari» — nima yaroqsiz bo'lmoqda. Do'konlardan qaytarishlarni ofis o'tkazadi; yetkazib beruvchiga qaytarish — «Kirim»dagi yetkazib beruvchi kartasidan.",
       "img": ("web", "operator", "warehouse")},
      {"ru": "Штрих-коды: печать этикеток на товары и по приходу; сканер-клавиатура работает везде, где есть поле поиска товара («код + Enter»).",
       "uz": "Shtrix-kodlar: tovarlarga va kirim bo'yicha yorliqlar chop etish; skaner-klaviatura tovar qidiruvi bor har joyda ishlaydi («kod + Enter»).",
       "img": ("web", "operator", "barcode")},
    ],
  },
  {
    "key": "ceo", "ru": "Директор", "uz": "Direktor",
    "intro": ("Пять вопросов директора — на первом экране: сколько продали и довезли сегодня, кто должен, что сгорает на складе, кто из агентов не работает, что с зарплатой.",
              "Direktorning beshta savoli — birinchi ekranda: bugun qancha sotildi va yetkazildi, kim qarzdor, omborda nima yaroqsiz bo'lmoqda, agentlardan kim ishlamayapti, oylik bilan nima gap."),
    "steps": [
      {"ru": "Главная: выручка и заказы за сегодня (стрелка — к вчера), «довезено N из M», долг клиентов, маржа. Алерты ниже кликаются: просрочка — в отчёты по складу, долг — в «Долги».",
       "uz": "Bosh sahifa: bugungi tushum va buyurtmalar (strelka — kechaga nisbatan), «yetkazildi N / M», mijozlar qarzi, marja. Pastdagi ogohlantirishlar bosiladi: muddati o'tgan — ombor hisobotlariga, qarz — «Qarzlar»ga.",
       "img": ("web", "ceo", "dashboard")},
      {"ru": "KPI агентов: таблица с баллами, продажами, визитами; клик по агенту — разбор и его зарплата за период. Колонка «GPS» — у кого нет следов на карте.",
       "uz": "Agentlar KPI: ballar, sotuvlar, tashriflar jadvali; agentga bosilsa — tahlil va uning davr uchun oyligi. «GPS» ustuni — kimning xaritada izi yo'q.",
       "img": ("web", "ceo", "kpi")},
      {"ru": "Карта: кто на связи, кто был раньше, кто без сигнала; маршрут агента за день, фото визитов, «подмена координат» — красным.",
       "uz": "Xarita: kim aloqada, kim oldin bo'lgan, kim signalsiz; agentning kunlik yo'nalishi, tashrif fotolari, «koordinatalar almashtirilgan» — qizil.",
       "img": ("web", "ceo", "map")},
      {"ru": "Отчёты и долги: «Долги» — кто, сколько и как давно; строка ведёт в карточку магазина. P&L — заработали или потеряли за период.",
       "uz": "Hisobotlar va qarzlar: «Qarzlar» — kim, qancha va qachondan beri; qator do'kon kartasiga olib boradi. P&L — davr uchun foyda yoki zarar.",
       "img": ("web", "ceo", "reports-debts")},
      {"ru": "Зарплаты: фонд, начислено и выдано; «Выдать всем» с подтверждением получения сотрудником на телефоне. Настройка оклада и процентов — там же.",
       "uz": "Oyliklar: fond, hisoblangan va berilgan; «Hammaga berish» — xodim telefonda olganini tasdiqlaydi. Maosh va foizlar sozlamasi — o'sha yerda.",
       "img": ("web", "ceo", "salaries")},
      {"ru": "Пользователи и журнал действий: кто что сделал — отмена заказа, сторно оплаты, смена лимита; фильтры «Заказы / Оплаты / Магазины».",
       "uz": "Foydalanuvchilar va amallar jurnali: kim nima qildi — buyurtma bekor qilindi, to'lov storno qilindi, limit o'zgardi; «Buyurtmalar / To'lovlar / Do'konlar» filtrlari.",
       "img": ("web", "ceo", "audit-log")},
    ],
  },
  {
    "key": "supervisor", "ru": "Супервайзер", "uz": "Supervayzer",
    "intro": ("Утро — карта: кто вышел. Месяц — планы визитов одной кнопкой. Вечер — разбор дня по координатам.",
              "Ertalab — xarita: kim ishga chiqdi. Oy — bitta tugma bilan tashrif rejalari. Kechqurun — koordinatalar bo'yicha kun tahlili."),
    "steps": [
      {"ru": "Карта (веб): состав команды целиком — «На связи / Были раньше / Без сигнала»; у каждого — обход x/y за день и % нормы.",
       "uz": "Xarita (veb): butun jamoa — «Aloqada / Oldin bo'lgan / Signalsiz»; har birida — kunlik aylanish x/y va norma foizi.",
       "img": ("web", "supervisor", "map")},
      {"ru": "Планы: вкладка «Месяц» — агент, территория, дни недели → «Расставить»; вкладка «День» — «Как прошёл день»: время в точках, километры, замечания.",
       "uz": "Rejalar: «Oy» bo'limi — agent, hudud, hafta kunlari → «Joylashtirish»; «Kun» bo'limi — «Kun qanday o'tdi»: nuqtalardagi vaqt, kilometrlar, izohlar.",
       "img": ("web", "supervisor", "plans")},
      {"ru": "Телефон: «Карта», «Планы», «Нормы» — то же в дороге.",
       "uz": "Telefon: «Xarita», «Rejalar», «Normalar» — yo'lda ham o'sha.",
       "img": ("mobile", "supervisor", "map")},
    ],
  },
  {
    "key": "agent", "ru": "Торговый агент (телефон)", "uz": "Savdo agenti (telefon)",
    "intro": ("30–60 визитов в день. Главная — визиты и долги; заказ у прилавка за минуту; всё работает без связи и отправляется само.",
              "Kuniga 30–60 tashrif. Bosh sahifa — tashriflar va qarzlar; peshtaxta oldida bir daqiqada buyurtma; hammasi aloqasiz ishlaydi va o'zi jo'natiladi."),
    "steps": [
      {"ru": "Главная: визиты на сегодня (строка ведёт в магазин), плитка «Долги» — кому идти собирать, выручка и заказы за день.",
       "uz": "Bosh sahifa: bugungi tashriflar (qator do'konga olib boradi), «Qarzlar» plitkasi — kimdan undirish kerak, kunlik tushum va buyurtmalar.",
       "img": ("mobile", "agent", "home")},
      {"ru": "Магазины: ближайшие первыми, корзина на карточке — заказ в один тап. Новый магазин заводится прямо у точки.",
       "uz": "Do'konlar: yaqinlari birinchi, kartadagi savat — bir teginishda buyurtma. Yangi do'kon nuqtaning o'zida ochiladi.",
       "img": ("mobile", "agent", "shops")},
      {"ru": "Новый заказ — три шага: магазин → товары (поиск, сканер, «− n +», виден остаток) → оплата и обещанный срок → Подтвердить.",
       "uz": "Yangi buyurtma — uch qadam: do'kon → tovarlar (qidiruv, skaner, «− n +», qoldiq ko'rinadi) → to'lov va va'da qilingan muddat → Tasdiqlash.",
       "img": ("mobile", "agent", "order-new")},
      {"ru": "Без связи: список магазинов и каталог берутся из копии на телефоне (с датой), заказ ложится в очередь и уходит сам. В «Заказах» отложенные видны карточками «ожидает отправки».",
       "uz": "Aloqasiz: do'konlar ro'yxati va katalog telefondagi nusxadan olinadi (sanasi bilan), buyurtma navbatga tushadi va o'zi jo'natiladi. «Buyurtmalar»da kechiktirilganlar «jo'natish kutilmoqda» kartalari bilan ko'rinadi.",
       "img": ("mobile", "agent", "orders")},
      {"ru": "План: «Готово» отмечает визит (с фото или без); без связи отметка сохраняется и уйдёт сама. Долги: список должников, звонок в один тап.",
       "uz": "Reja: «Tayyor» tashrifni belgilaydi (foto bilan yoki fotosiz); aloqasiz belgi saqlanadi va o'zi ketadi. Qarzlar: qarzdorlar ro'yxati, bir teginishda qo'ng'iroq.",
       "img": ("mobile", "agent", "debts")},
      {"ru": "Зарплата: начислено за период, выдано на руки — «Получил» подтверждает выплату.",
       "uz": "Oylik: davr uchun hisoblangan, qo'lga berilgan — «Oldim» to'lovni tasdiqlaydi.",
       "img": ("mobile", "agent", "salary")},
    ],
  },
  {
    "key": "courier", "ru": "Курьер (телефон)", "uz": "Kuryer (telefon)",
    "intro": ("Утром — «Выехал по всем». У точки — сумма наличных и «Доставлено», либо «Не доставлено» с причиной, либо «Оформить подробно» для частичной оплаты и возврата. Всё — без связи.",
              "Ertalab — «Hammasiga yo'lga chiqdim». Nuqtada — naqd summa va «Yetkazildi», yoki sababi bilan «Yetkazilmadi», yoki qisman to'lov va qaytarish uchun «Batafsil rasmiylashtirish». Hammasi — aloqasiz."),
    "steps": [
      {"ru": "Доставки: сверху «Ожидают N · В пути M», кнопка «Выехал по всем». Карточка: адрес, «На карте» (маршрут по координатам), сумма, состав заказа.",
       "uz": "Yetkazishlar: yuqorida «Kutmoqda N · Yo'lda M», «Hammasiga yo'lga chiqdim» tugmasi. Karta: manzil, «Xaritada» (koordinatalar bo'yicha yo'nalish), summa, buyurtma tarkibi.",
       "img": ("mobile", "courier", "deliveries")},
      {"ru": "Частичный возврат оформляется вместе с деньгами: что вернулось по позициям, сколько заплатили за оставшееся, когда доплатят. Дату можно писать как привыкли — 15.09.2026.",
       "uz": "Qisman qaytarish pul bilan birga rasmiylashtiriladi: qaysi tovarlar qaytdi, qolgani uchun qancha to'landi, qachon qo'shimcha to'lanadi. Sanani odatdagidek yozish mumkin — 15.09.2026.",
       "img": None},
      {"ru": "Отметка, которую сервер отклонил (например, заказ уже закрыт), показывает причину и кнопки «Повторить / Убрать». Зарплата — на Главной.",
       "uz": "Server rad etgan belgi (masalan, buyurtma allaqachon yopilgan) sababi va «Qayta / Olib tashlash» tugmalarini ko'rsatadi. Oylik — Bosh sahifada.",
       "img": ("mobile", "courier", "home")},
    ],
  },
  {
    "key": "merchandiser", "ru": "Мерчандайзер (телефон)", "uz": "Merchandayzer (telefon)",
    "intro": ("План на день → в точке «Готово» открывает отчёт: фото полки, чек-лист товаров с ценой и акцией, заметки.",
              "Kunlik reja → nuqtada «Tayyor» hisobotni ochadi: javon fotosi, narx va aksiya bilan tovarlar ro'yxati, izohlar."),
    "steps": [
      {"ru": "Главная и План: только визиты, магазины и профиль — без чужих блоков про продажи.",
       "uz": "Bosh sahifa va Reja: faqat tashriflar, do'konlar va profil — sotuv haqidagi begona bloklarsiz.",
       "img": ("mobile", "merchandiser", "plan")},
      {"ru": "Отчёт о визите: снимок с камеры, отметки по товарам, «Завершить визит». Черновик хранится сутки, если отвлеклись.",
       "uz": "Tashrif hisoboti: kameradan surat, tovarlar bo'yicha belgilar, «Tashrifni yakunlash». Chalg'isangiz, qoralama bir kun saqlanadi.",
       "img": ("mobile", "merchandiser", "home")},
    ],
  },
]
